packages:
  - "."

allowBuilds:
  '@openrouter/sdk': true
  '@prisma/engines': true
  esbuild: true
  msw: false
  prisma: true
  sharp: true
  workerd: true
onlyBuiltDependencies:
  - "@prisma/engines"
  - esbuild
  - lightningcss
  - prisma
  - sharp
  - workerd
