export const dataScopes = {
  ALL: "all",
  TENANT: "tenant",
  ORG_TREE: "org_tree",
  ASSIGNED_PROJECTS: "assigned_projects",
  READONLY_PUBLIC: "readonly_public",
} as const

export type DataScope = (typeof dataScopes)[keyof typeof dataScopes]

export const dataScopeDefinitions = {
  [dataScopes.ALL]: {
    label: "All platform data",
    description: "Platform administrator access across tenants.",
  },
  [dataScopes.TENANT]: {
    label: "Current tenant",
    description: "Access limited to the current tenant.",
  },
  [dataScopes.ORG_TREE]: {
    label: "Current organization tree",
    description: "Access limited to the current organization and descendants.",
  },
  [dataScopes.ASSIGNED_PROJECTS]: {
    label: "Assigned projects",
    description: "Access limited to projects assigned to the user.",
  },
  [dataScopes.READONLY_PUBLIC]: {
    label: "Readonly public data",
    description: "Readonly access for public, supervision, or teaching views.",
  },
} as const satisfies Record<DataScope, { label: string; description: string }>

export const permissionCodes = {
  TENANT_USER_READ: "tenant:user:read",
  TENANT_USER_WRITE: "tenant:user:write",
  TENANT_ROLE_READ: "tenant:role:read",
  TENANT_ROLE_WRITE: "tenant:role:write",
  PROJECT_SITE_READ: "project:site:read",
  PROJECT_SITE_WRITE: "project:site:write",
  STANDARD_DICTIONARY_READ: "standard:dictionary:read",
  STANDARD_RULE_READ: "standard:rule:read",
  DEVICE_TELEMETRY_READ: "device:telemetry:read",
  ALERT_READ: "alert:read",
  ALERT_WRITE: "alert:write",
  AGRI_TASK_WRITE: "agri:task:write",
  AI_REVIEW_WRITE: "ai:review:write",
  DEVICE_CONTROL_REQUEST: "device:control:request",
  ALERT_RULE_WRITE: "alert:rule:write",
  PROVIDER_SYNC_READ: "provider:sync:read",
  PROVIDER_SYNC_WRITE: "provider:sync:write",
  TRACE_ARCHIVE_EXPORT: "trace:archive:export",
  SYSTEM_AUDIT_READ: "system:audit:read",
  SYSTEM_CONFIG_WRITE: "system:config:write",
} as const

export type PermissionCode =
  (typeof permissionCodes)[keyof typeof permissionCodes]

export const permissionDefinitions = {
  [permissionCodes.TENANT_USER_READ]: {
    domain: "tenant",
    resource: "user",
    action: "read",
    riskLevel: "normal",
  },
  [permissionCodes.TENANT_USER_WRITE]: {
    domain: "tenant",
    resource: "user",
    action: "write",
    riskLevel: "normal",
  },
  [permissionCodes.TENANT_ROLE_READ]: {
    domain: "tenant",
    resource: "role",
    action: "read",
    riskLevel: "normal",
  },
  [permissionCodes.TENANT_ROLE_WRITE]: {
    domain: "tenant",
    resource: "role",
    action: "write",
    riskLevel: "normal",
  },
  [permissionCodes.PROJECT_SITE_READ]: {
    domain: "project",
    resource: "site",
    action: "read",
    riskLevel: "normal",
  },
  [permissionCodes.PROJECT_SITE_WRITE]: {
    domain: "project",
    resource: "site",
    action: "write",
    riskLevel: "normal",
  },
  [permissionCodes.STANDARD_DICTIONARY_READ]: {
    domain: "standard",
    resource: "dictionary",
    action: "read",
    riskLevel: "normal",
  },
  [permissionCodes.STANDARD_RULE_READ]: {
    domain: "standard",
    resource: "rule",
    action: "read",
    riskLevel: "normal",
  },
  [permissionCodes.DEVICE_TELEMETRY_READ]: {
    domain: "device",
    resource: "telemetry",
    action: "read",
    riskLevel: "normal",
  },
  [permissionCodes.ALERT_READ]: {
    domain: "alert",
    resource: "alert",
    action: "read",
    riskLevel: "normal",
  },
  [permissionCodes.ALERT_WRITE]: {
    domain: "alert",
    resource: "alert",
    action: "write",
    riskLevel: "normal",
  },
  [permissionCodes.AGRI_TASK_WRITE]: {
    domain: "agri",
    resource: "task",
    action: "write",
    riskLevel: "normal",
  },
  [permissionCodes.AI_REVIEW_WRITE]: {
    domain: "ai",
    resource: "review",
    action: "write",
    riskLevel: "high",
  },
  [permissionCodes.DEVICE_CONTROL_REQUEST]: {
    domain: "device",
    resource: "control",
    action: "request",
    riskLevel: "high",
  },
  [permissionCodes.ALERT_RULE_WRITE]: {
    domain: "alert",
    resource: "rule",
    action: "write",
    riskLevel: "normal",
  },
  [permissionCodes.PROVIDER_SYNC_READ]: {
    domain: "provider",
    resource: "sync",
    action: "read",
    riskLevel: "normal",
  },
  [permissionCodes.PROVIDER_SYNC_WRITE]: {
    domain: "provider",
    resource: "sync",
    action: "write",
    riskLevel: "high",
  },
  [permissionCodes.TRACE_ARCHIVE_EXPORT]: {
    domain: "trace",
    resource: "archive",
    action: "export",
    riskLevel: "high",
  },
  [permissionCodes.SYSTEM_AUDIT_READ]: {
    domain: "system",
    resource: "audit",
    action: "read",
    riskLevel: "normal",
  },
  [permissionCodes.SYSTEM_CONFIG_WRITE]: {
    domain: "system",
    resource: "config",
    action: "write",
    riskLevel: "high",
  },
} as const satisfies Record<
  PermissionCode,
  {
    domain: string
    resource: string
    action: string
    riskLevel: "normal" | "high"
  }
>

export type ConsoleMenuItem = {
  id: string
  parentId: string | null
  title: string
  route: string
  icon: string
  permissionCode: PermissionCode | null
  order: number
  visible: boolean
}

export const consoleMenuItems = [
  {
    id: "dashboard",
    parentId: null,
    title: "工作台",
    route: "/console",
    icon: "layout-dashboard",
    permissionCode: null,
    order: 10,
    visible: true,
  },
  {
    id: "tenant",
    parentId: null,
    title: "租户与权限",
    route: "/console/tenant",
    icon: "shield-check",
    permissionCode: permissionCodes.TENANT_USER_READ,
    order: 20,
    visible: true,
  },
  {
    id: "tenant-users",
    parentId: "tenant",
    title: "用户管理",
    route: "/console/tenant/users",
    icon: "users",
    permissionCode: permissionCodes.TENANT_USER_READ,
    order: 21,
    visible: true,
  },
  {
    id: "tenant-roles",
    parentId: "tenant",
    title: "角色权限",
    route: "/console/tenant/roles",
    icon: "key-round",
    permissionCode: permissionCodes.TENANT_ROLE_READ,
    order: 22,
    visible: true,
  },
  {
    id: "tenant-menus",
    parentId: "tenant",
    title: "菜单权限",
    route: "/console/tenant/menus",
    icon: "list-tree",
    permissionCode: permissionCodes.TENANT_ROLE_READ,
    order: 23,
    visible: true,
  },
  {
    id: "tenant-data-scopes",
    parentId: "tenant",
    title: "数据范围",
    route: "/console/tenant/data-scopes",
    icon: "scan-eye",
    permissionCode: permissionCodes.TENANT_ROLE_READ,
    order: 24,
    visible: true,
  },
  {
    id: "assets",
    parentId: null,
    title: "基地资产",
    route: "/console/assets",
    icon: "map",
    permissionCode: permissionCodes.PROJECT_SITE_READ,
    order: 30,
    visible: true,
  },
  {
    id: "assets-sites",
    parentId: "assets",
    title: "项目基地",
    route: "/console/assets/sites",
    icon: "map-pinned",
    permissionCode: permissionCodes.PROJECT_SITE_READ,
    order: 31,
    visible: true,
  },
  {
    id: "assets-greenhouses",
    parentId: "assets",
    title: "大棚地块",
    route: "/console/assets/greenhouses",
    icon: "warehouse",
    permissionCode: permissionCodes.PROJECT_SITE_READ,
    order: 32,
    visible: true,
  },
  {
    id: "assets-devices",
    parentId: "assets",
    title: "设备台账",
    route: "/console/assets/devices",
    icon: "radio-tower",
    permissionCode: permissionCodes.DEVICE_TELEMETRY_READ,
    order: 33,
    visible: true,
  },
  {
    id: "standards",
    parentId: null,
    title: "标准与字典",
    route: "/console/standards",
    icon: "book-open",
    permissionCode: permissionCodes.STANDARD_DICTIONARY_READ,
    order: 40,
    visible: true,
  },
  {
    id: "standards-dictionary",
    parentId: "standards",
    title: "标准字典",
    route: "/console/standards/dictionary",
    icon: "book-open",
    permissionCode: permissionCodes.STANDARD_DICTIONARY_READ,
    order: 41,
    visible: true,
  },
  {
    id: "standards-metrics",
    parentId: "standards",
    title: "遥测指标",
    route: "/console/standards/metrics",
    icon: "gauge",
    permissionCode: permissionCodes.DEVICE_TELEMETRY_READ,
    order: 42,
    visible: true,
  },
  {
    id: "standards-validation",
    parentId: "standards",
    title: "规则校验",
    route: "/console/standards/validation",
    icon: "check-circle-2",
    permissionCode: permissionCodes.STANDARD_RULE_READ,
    order: 43,
    visible: true,
  },
  {
    id: "monitoring",
    parentId: null,
    title: "监测与告警",
    route: "/console/monitoring",
    icon: "activity",
    permissionCode: permissionCodes.DEVICE_TELEMETRY_READ,
    order: 50,
    visible: true,
  },
  {
    id: "monitoring-latest",
    parentId: "monitoring",
    title: "实时遥测",
    route: "/console/monitoring/latest",
    icon: "activity",
    permissionCode: permissionCodes.DEVICE_TELEMETRY_READ,
    order: 51,
    visible: true,
  },
  {
    id: "monitoring-history",
    parentId: "monitoring",
    title: "历史查询",
    route: "/console/monitoring/history",
    icon: "history",
    permissionCode: permissionCodes.DEVICE_TELEMETRY_READ,
    order: 52,
    visible: true,
  },
  {
    id: "monitoring-alerts",
    parentId: "monitoring",
    title: "告警中心",
    route: "/console/monitoring/alerts",
    icon: "bell",
    permissionCode: permissionCodes.ALERT_READ,
    order: 53,
    visible: true,
  },
  {
    id: "monitoring-rules",
    parentId: "monitoring",
    title: "规则管理",
    route: "/console/monitoring/rules",
    icon: "sliders-horizontal",
    permissionCode: permissionCodes.STANDARD_RULE_READ,
    order: 54,
    visible: true,
  },
  {
    id: "providers",
    parentId: null,
    title: "同步与供应商",
    route: "/console/providers",
    icon: "refresh-cw",
    permissionCode: permissionCodes.PROVIDER_SYNC_READ,
    order: 60,
    visible: true,
  },
  {
    id: "providers-renke",
    parentId: "providers",
    title: "Renke 同步",
    route: "/console/providers/renke",
    icon: "cloud-cog",
    permissionCode: permissionCodes.PROVIDER_SYNC_READ,
    order: 61,
    visible: true,
  },
  {
    id: "providers-runs",
    parentId: "providers",
    title: "同步记录",
    route: "/console/providers/runs",
    icon: "list-checks",
    permissionCode: permissionCodes.PROVIDER_SYNC_READ,
    order: 62,
    visible: true,
  },
  {
    id: "system",
    parentId: null,
    title: "系统与审计",
    route: "/console/system",
    icon: "settings",
    permissionCode: permissionCodes.SYSTEM_AUDIT_READ,
    order: 90,
    visible: true,
  },
  {
    id: "system-audit",
    parentId: "system",
    title: "审计日志",
    route: "/console/system/audit",
    icon: "history",
    permissionCode: permissionCodes.SYSTEM_AUDIT_READ,
    order: 91,
    visible: true,
  },
  {
    id: "system-runtime",
    parentId: "system",
    title: "运行状态",
    route: "/console/system/runtime",
    icon: "server-cog",
    permissionCode: permissionCodes.SYSTEM_AUDIT_READ,
    order: 92,
    visible: true,
  },
  {
    id: "system-compliance",
    parentId: "system",
    title: "发布合规",
    route: "/console/system/compliance",
    icon: "file-check-2",
    permissionCode: permissionCodes.SYSTEM_AUDIT_READ,
    order: 93,
    visible: true,
  },
] as const satisfies readonly ConsoleMenuItem[]

export const rbacTableNames = {
  TENANTS: "heos_tenants",
  ORG_UNITS: "heos_org_units",
  USERS: "heos_users",
  POSTS: "heos_posts",
  ROLES: "heos_roles",
  MENUS: "heos_menus",
  PERMISSIONS: "heos_permissions",
  ROLE_PERMISSIONS: "heos_role_permissions",
  USER_ROLES: "heos_user_roles",
  DATA_SCOPES: "heos_data_scopes",
  ROLE_DATA_SCOPES: "heos_role_data_scopes",
  AUDIT_LOGS: "heos_audit_logs",
} as const

export type RbacTableName = (typeof rbacTableNames)[keyof typeof rbacTableNames]
