/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoPrismaRouteImport } from './routes/demo/prisma'
import { Route as DemoNeonRouteImport } from './routes/demo/neon'
import { Route as ApiTelemetryLatestRouteImport } from './routes/api/telemetry/latest'
import { Route as ApiTelemetryHistoryRouteImport } from './routes/api/telemetry/history'
import { Route as ApiComplianceChecklistRouteImport } from './routes/api/compliance/checklist'
import { Route as ApiProvidersRenkeSyncRouteImport } from './routes/api/providers/renke/sync'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPrismaRoute = DemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNeonRoute = DemoNeonRouteImport.update({
  id: '/demo/neon',
  path: '/demo/neon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelemetryLatestRoute = ApiTelemetryLatestRouteImport.update({
  id: '/api/telemetry/latest',
  path: '/api/telemetry/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelemetryHistoryRoute = ApiTelemetryHistoryRouteImport.update({
  id: '/api/telemetry/history',
  path: '/api/telemetry/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComplianceChecklistRoute = ApiComplianceChecklistRouteImport.update({
  id: '/api/compliance/checklist',
  path: '/api/compliance/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvidersRenkeSyncRoute = ApiProvidersRenkeSyncRouteImport.update({
  id: '/api/providers/renke/sync',
  path: '/api/providers/renke/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/console': typeof ConsoleRoute
  '/login': typeof LoginRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/api/compliance/checklist': typeof ApiComplianceChecklistRoute
  '/api/telemetry/history': typeof ApiTelemetryHistoryRoute
  '/api/telemetry/latest': typeof ApiTelemetryLatestRoute
  '/api/providers/renke/sync': typeof ApiProvidersRenkeSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/console': typeof ConsoleRoute
  '/login': typeof LoginRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/api/compliance/checklist': typeof ApiComplianceChecklistRoute
  '/api/telemetry/history': typeof ApiTelemetryHistoryRoute
  '/api/telemetry/latest': typeof ApiTelemetryLatestRoute
  '/api/providers/renke/sync': typeof ApiProvidersRenkeSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/console': typeof ConsoleRoute
  '/login': typeof LoginRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/api/compliance/checklist': typeof ApiComplianceChecklistRoute
  '/api/telemetry/history': typeof ApiTelemetryHistoryRoute
  '/api/telemetry/latest': typeof ApiTelemetryLatestRoute
  '/api/providers/renke/sync': typeof ApiProvidersRenkeSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/console'
    | '/login'
    | '/demo/neon'
    | '/demo/prisma'
    | '/api/compliance/checklist'
    | '/api/telemetry/history'
    | '/api/telemetry/latest'
    | '/api/providers/renke/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/console'
    | '/login'
    | '/demo/neon'
    | '/demo/prisma'
    | '/api/compliance/checklist'
    | '/api/telemetry/history'
    | '/api/telemetry/latest'
    | '/api/providers/renke/sync'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/console'
    | '/login'
    | '/demo/neon'
    | '/demo/prisma'
    | '/api/compliance/checklist'
    | '/api/telemetry/history'
    | '/api/telemetry/latest'
    | '/api/providers/renke/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConsoleRoute: typeof ConsoleRoute
  LoginRoute: typeof LoginRoute
  DemoNeonRoute: typeof DemoNeonRoute
  DemoPrismaRoute: typeof DemoPrismaRoute
  ApiComplianceChecklistRoute: typeof ApiComplianceChecklistRoute
  ApiTelemetryHistoryRoute: typeof ApiTelemetryHistoryRoute
  ApiTelemetryLatestRoute: typeof ApiTelemetryLatestRoute
  ApiProvidersRenkeSyncRoute: typeof ApiProvidersRenkeSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/prisma': {
      id: '/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoPrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/neon': {
      id: '/demo/neon'
      path: '/demo/neon'
      fullPath: '/demo/neon'
      preLoaderRoute: typeof DemoNeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry/latest': {
      id: '/api/telemetry/latest'
      path: '/api/telemetry/latest'
      fullPath: '/api/telemetry/latest'
      preLoaderRoute: typeof ApiTelemetryLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry/history': {
      id: '/api/telemetry/history'
      path: '/api/telemetry/history'
      fullPath: '/api/telemetry/history'
      preLoaderRoute: typeof ApiTelemetryHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compliance/checklist': {
      id: '/api/compliance/checklist'
      path: '/api/compliance/checklist'
      fullPath: '/api/compliance/checklist'
      preLoaderRoute: typeof ApiComplianceChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/providers/renke/sync': {
      id: '/api/providers/renke/sync'
      path: '/api/providers/renke/sync'
      fullPath: '/api/providers/renke/sync'
      preLoaderRoute: typeof ApiProvidersRenkeSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConsoleRoute: ConsoleRoute,
  LoginRoute: LoginRoute,
  DemoNeonRoute: DemoNeonRoute,
  DemoPrismaRoute: DemoPrismaRoute,
  ApiComplianceChecklistRoute: ApiComplianceChecklistRoute,
  ApiTelemetryHistoryRoute: ApiTelemetryHistoryRoute,
  ApiTelemetryLatestRoute: ApiTelemetryLatestRoute,
  ApiProvidersRenkeSyncRoute: ApiProvidersRenkeSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
