/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TraceSlugRouteImport } from './routes/trace/$slug'
import { Route as DemoPrismaRouteImport } from './routes/demo/prisma'
import { Route as DemoNeonRouteImport } from './routes/demo/neon'
import { Route as ApiTelemetryLatestRouteImport } from './routes/api/telemetry/latest'
import { Route as ApiTelemetryHistoryRouteImport } from './routes/api/telemetry/history'
import { Route as ApiCoreTraceArchivesRouteImport } from './routes/api/core/trace-archives'
import { Route as ApiCoreProjectRouteImport } from './routes/api/core/project'
import { Route as ApiCoreDevicesRouteImport } from './routes/api/core/devices'
import { Route as ApiCoreDashboardRouteImport } from './routes/api/core/dashboard'
import { Route as ApiCoreAlertsRouteImport } from './routes/api/core/alerts'
import { Route as ApiCoreAiInteractionsRouteImport } from './routes/api/core/ai-interactions'
import { Route as ApiCoreAgriTasksRouteImport } from './routes/api/core/agri-tasks'
import { Route as ApiComplianceChecklistRouteImport } from './routes/api/compliance/checklist'
import { Route as ApiProvidersRenkeSyncRouteImport } from './routes/api/providers/renke/sync'
import { Route as ApiProvidersRenkeReplayRouteImport } from './routes/api/providers/renke/replay'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceSlugRoute = TraceSlugRouteImport.update({
  id: '/trace/$slug',
  path: '/trace/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPrismaRoute = DemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNeonRoute = DemoNeonRouteImport.update({
  id: '/demo/neon',
  path: '/demo/neon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelemetryLatestRoute = ApiTelemetryLatestRouteImport.update({
  id: '/api/telemetry/latest',
  path: '/api/telemetry/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelemetryHistoryRoute = ApiTelemetryHistoryRouteImport.update({
  id: '/api/telemetry/history',
  path: '/api/telemetry/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoreTraceArchivesRoute = ApiCoreTraceArchivesRouteImport.update({
  id: '/api/core/trace-archives',
  path: '/api/core/trace-archives',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoreProjectRoute = ApiCoreProjectRouteImport.update({
  id: '/api/core/project',
  path: '/api/core/project',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoreDevicesRoute = ApiCoreDevicesRouteImport.update({
  id: '/api/core/devices',
  path: '/api/core/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoreDashboardRoute = ApiCoreDashboardRouteImport.update({
  id: '/api/core/dashboard',
  path: '/api/core/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoreAlertsRoute = ApiCoreAlertsRouteImport.update({
  id: '/api/core/alerts',
  path: '/api/core/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoreAiInteractionsRoute = ApiCoreAiInteractionsRouteImport.update({
  id: '/api/core/ai-interactions',
  path: '/api/core/ai-interactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoreAgriTasksRoute = ApiCoreAgriTasksRouteImport.update({
  id: '/api/core/agri-tasks',
  path: '/api/core/agri-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComplianceChecklistRoute = ApiComplianceChecklistRouteImport.update({
  id: '/api/compliance/checklist',
  path: '/api/compliance/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvidersRenkeSyncRoute = ApiProvidersRenkeSyncRouteImport.update({
  id: '/api/providers/renke/sync',
  path: '/api/providers/renke/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvidersRenkeReplayRoute = ApiProvidersRenkeReplayRouteImport.update({
  id: '/api/providers/renke/replay',
  path: '/api/providers/renke/replay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/console': typeof ConsoleRoute
  '/login': typeof LoginRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/trace/$slug': typeof TraceSlugRoute
  '/api/compliance/checklist': typeof ApiComplianceChecklistRoute
  '/api/core/agri-tasks': typeof ApiCoreAgriTasksRoute
  '/api/core/ai-interactions': typeof ApiCoreAiInteractionsRoute
  '/api/core/alerts': typeof ApiCoreAlertsRoute
  '/api/core/dashboard': typeof ApiCoreDashboardRoute
  '/api/core/devices': typeof ApiCoreDevicesRoute
  '/api/core/project': typeof ApiCoreProjectRoute
  '/api/core/trace-archives': typeof ApiCoreTraceArchivesRoute
  '/api/telemetry/history': typeof ApiTelemetryHistoryRoute
  '/api/telemetry/latest': typeof ApiTelemetryLatestRoute
  '/api/providers/renke/replay': typeof ApiProvidersRenkeReplayRoute
  '/api/providers/renke/sync': typeof ApiProvidersRenkeSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/console': typeof ConsoleRoute
  '/login': typeof LoginRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/trace/$slug': typeof TraceSlugRoute
  '/api/compliance/checklist': typeof ApiComplianceChecklistRoute
  '/api/core/agri-tasks': typeof ApiCoreAgriTasksRoute
  '/api/core/ai-interactions': typeof ApiCoreAiInteractionsRoute
  '/api/core/alerts': typeof ApiCoreAlertsRoute
  '/api/core/dashboard': typeof ApiCoreDashboardRoute
  '/api/core/devices': typeof ApiCoreDevicesRoute
  '/api/core/project': typeof ApiCoreProjectRoute
  '/api/core/trace-archives': typeof ApiCoreTraceArchivesRoute
  '/api/telemetry/history': typeof ApiTelemetryHistoryRoute
  '/api/telemetry/latest': typeof ApiTelemetryLatestRoute
  '/api/providers/renke/replay': typeof ApiProvidersRenkeReplayRoute
  '/api/providers/renke/sync': typeof ApiProvidersRenkeSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/console': typeof ConsoleRoute
  '/login': typeof LoginRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/trace/$slug': typeof TraceSlugRoute
  '/api/compliance/checklist': typeof ApiComplianceChecklistRoute
  '/api/core/agri-tasks': typeof ApiCoreAgriTasksRoute
  '/api/core/ai-interactions': typeof ApiCoreAiInteractionsRoute
  '/api/core/alerts': typeof ApiCoreAlertsRoute
  '/api/core/dashboard': typeof ApiCoreDashboardRoute
  '/api/core/devices': typeof ApiCoreDevicesRoute
  '/api/core/project': typeof ApiCoreProjectRoute
  '/api/core/trace-archives': typeof ApiCoreTraceArchivesRoute
  '/api/telemetry/history': typeof ApiTelemetryHistoryRoute
  '/api/telemetry/latest': typeof ApiTelemetryLatestRoute
  '/api/providers/renke/replay': typeof ApiProvidersRenkeReplayRoute
  '/api/providers/renke/sync': typeof ApiProvidersRenkeSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/console'
    | '/login'
    | '/demo/neon'
    | '/demo/prisma'
    | '/trace/$slug'
    | '/api/compliance/checklist'
    | '/api/core/agri-tasks'
    | '/api/core/ai-interactions'
    | '/api/core/alerts'
    | '/api/core/dashboard'
    | '/api/core/devices'
    | '/api/core/project'
    | '/api/core/trace-archives'
    | '/api/telemetry/history'
    | '/api/telemetry/latest'
    | '/api/providers/renke/replay'
    | '/api/providers/renke/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/console'
    | '/login'
    | '/demo/neon'
    | '/demo/prisma'
    | '/trace/$slug'
    | '/api/compliance/checklist'
    | '/api/core/agri-tasks'
    | '/api/core/ai-interactions'
    | '/api/core/alerts'
    | '/api/core/dashboard'
    | '/api/core/devices'
    | '/api/core/project'
    | '/api/core/trace-archives'
    | '/api/telemetry/history'
    | '/api/telemetry/latest'
    | '/api/providers/renke/replay'
    | '/api/providers/renke/sync'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/console'
    | '/login'
    | '/demo/neon'
    | '/demo/prisma'
    | '/trace/$slug'
    | '/api/compliance/checklist'
    | '/api/core/agri-tasks'
    | '/api/core/ai-interactions'
    | '/api/core/alerts'
    | '/api/core/dashboard'
    | '/api/core/devices'
    | '/api/core/project'
    | '/api/core/trace-archives'
    | '/api/telemetry/history'
    | '/api/telemetry/latest'
    | '/api/providers/renke/replay'
    | '/api/providers/renke/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConsoleRoute: typeof ConsoleRoute
  LoginRoute: typeof LoginRoute
  DemoNeonRoute: typeof DemoNeonRoute
  DemoPrismaRoute: typeof DemoPrismaRoute
  TraceSlugRoute: typeof TraceSlugRoute
  ApiComplianceChecklistRoute: typeof ApiComplianceChecklistRoute
  ApiCoreAgriTasksRoute: typeof ApiCoreAgriTasksRoute
  ApiCoreAiInteractionsRoute: typeof ApiCoreAiInteractionsRoute
  ApiCoreAlertsRoute: typeof ApiCoreAlertsRoute
  ApiCoreDashboardRoute: typeof ApiCoreDashboardRoute
  ApiCoreDevicesRoute: typeof ApiCoreDevicesRoute
  ApiCoreProjectRoute: typeof ApiCoreProjectRoute
  ApiCoreTraceArchivesRoute: typeof ApiCoreTraceArchivesRoute
  ApiTelemetryHistoryRoute: typeof ApiTelemetryHistoryRoute
  ApiTelemetryLatestRoute: typeof ApiTelemetryLatestRoute
  ApiProvidersRenkeReplayRoute: typeof ApiProvidersRenkeReplayRoute
  ApiProvidersRenkeSyncRoute: typeof ApiProvidersRenkeSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace/$slug': {
      id: '/trace/$slug'
      path: '/trace/$slug'
      fullPath: '/trace/$slug'
      preLoaderRoute: typeof TraceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/prisma': {
      id: '/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoPrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/neon': {
      id: '/demo/neon'
      path: '/demo/neon'
      fullPath: '/demo/neon'
      preLoaderRoute: typeof DemoNeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry/latest': {
      id: '/api/telemetry/latest'
      path: '/api/telemetry/latest'
      fullPath: '/api/telemetry/latest'
      preLoaderRoute: typeof ApiTelemetryLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry/history': {
      id: '/api/telemetry/history'
      path: '/api/telemetry/history'
      fullPath: '/api/telemetry/history'
      preLoaderRoute: typeof ApiTelemetryHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/core/trace-archives': {
      id: '/api/core/trace-archives'
      path: '/api/core/trace-archives'
      fullPath: '/api/core/trace-archives'
      preLoaderRoute: typeof ApiCoreTraceArchivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/core/project': {
      id: '/api/core/project'
      path: '/api/core/project'
      fullPath: '/api/core/project'
      preLoaderRoute: typeof ApiCoreProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/core/devices': {
      id: '/api/core/devices'
      path: '/api/core/devices'
      fullPath: '/api/core/devices'
      preLoaderRoute: typeof ApiCoreDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/core/dashboard': {
      id: '/api/core/dashboard'
      path: '/api/core/dashboard'
      fullPath: '/api/core/dashboard'
      preLoaderRoute: typeof ApiCoreDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/core/alerts': {
      id: '/api/core/alerts'
      path: '/api/core/alerts'
      fullPath: '/api/core/alerts'
      preLoaderRoute: typeof ApiCoreAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/core/ai-interactions': {
      id: '/api/core/ai-interactions'
      path: '/api/core/ai-interactions'
      fullPath: '/api/core/ai-interactions'
      preLoaderRoute: typeof ApiCoreAiInteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/core/agri-tasks': {
      id: '/api/core/agri-tasks'
      path: '/api/core/agri-tasks'
      fullPath: '/api/core/agri-tasks'
      preLoaderRoute: typeof ApiCoreAgriTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compliance/checklist': {
      id: '/api/compliance/checklist'
      path: '/api/compliance/checklist'
      fullPath: '/api/compliance/checklist'
      preLoaderRoute: typeof ApiComplianceChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/providers/renke/sync': {
      id: '/api/providers/renke/sync'
      path: '/api/providers/renke/sync'
      fullPath: '/api/providers/renke/sync'
      preLoaderRoute: typeof ApiProvidersRenkeSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/providers/renke/replay': {
      id: '/api/providers/renke/replay'
      path: '/api/providers/renke/replay'
      fullPath: '/api/providers/renke/replay'
      preLoaderRoute: typeof ApiProvidersRenkeReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConsoleRoute: ConsoleRoute,
  LoginRoute: LoginRoute,
  DemoNeonRoute: DemoNeonRoute,
  DemoPrismaRoute: DemoPrismaRoute,
  TraceSlugRoute: TraceSlugRoute,
  ApiComplianceChecklistRoute: ApiComplianceChecklistRoute,
  ApiCoreAgriTasksRoute: ApiCoreAgriTasksRoute,
  ApiCoreAiInteractionsRoute: ApiCoreAiInteractionsRoute,
  ApiCoreAlertsRoute: ApiCoreAlertsRoute,
  ApiCoreDashboardRoute: ApiCoreDashboardRoute,
  ApiCoreDevicesRoute: ApiCoreDevicesRoute,
  ApiCoreProjectRoute: ApiCoreProjectRoute,
  ApiCoreTraceArchivesRoute: ApiCoreTraceArchivesRoute,
  ApiTelemetryHistoryRoute: ApiTelemetryHistoryRoute,
  ApiTelemetryLatestRoute: ApiTelemetryLatestRoute,
  ApiProvidersRenkeReplayRoute: ApiProvidersRenkeReplayRoute,
  ApiProvidersRenkeSyncRoute: ApiProvidersRenkeSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
